import { ArrowUpRight, Check, CircleAlert, Code2, Cpu, Database, GitBranch, Globe2, Layers3, LockKeyhole, Play, Settings2, Terminal, Workflow } from 'lucide-react'
import styles from './design-system.module.css'

const nav = ['Home', 'Console', 'Build', 'Automate', 'Deploy', 'Integrate', 'Secure', 'Observe', 'Docs']
const screens = ['Home', 'Docs', 'Console', 'Project', 'Agent', 'Code Space', 'Workflow', 'Deployment', 'API', 'Settings', 'Security', 'Integrations', 'Billing', 'Team', 'Audit']
const components = [
  ['Navigation', Layers3], ['Code', Code2], ['Runtime', Cpu], ['Workflow', Workflow], ['Repository', GitBranch], ['Deploy', Globe2], ['Data', Database], ['Security', LockKeyhole],
] as const

export function VelclawDesignSystem() {
  return <main className={styles.page}>
    <header className={styles.topbar}><div className={styles.brand}><span className={styles.mark}>V</span><strong>velclaw</strong></div><nav>{nav.slice(1, 7).map(item => <a href={`#${item.toLowerCase()}`} key={item}>{item}</a>)}</nav><button className={styles.iconButton} aria-label="Settings"><Settings2 size={16} /></button></header>
    <section className={styles.hero}><div><p className={styles.eyebrow}>DESIGN SYSTEM / V1</p><h1>Build. Run.<br /><em>Understand.</em></h1><p className={styles.lead}>The visual language for Velclaw's AI-native software lifecycle workspace.</p><div className={styles.actions}><button className={styles.primary}>Create project <ArrowUpRight size={16} /></button><button className={styles.secondary}>Explore docs</button></div></div><div className={styles.heroPanel}><div className={styles.panelHeader}><span>VELCLAW / RUNTIME</span><span className={styles.live}>LIVE</span></div><div className={styles.vGraphic}><span>V</span></div><div className={styles.runtimeRow}><Check size={14} /> Workspace operational</div><div className={styles.runtimeRow}><Play size={14} /> Agent execution ready</div></div></section>
    <section className={styles.section}><div className={styles.sectionTitle}><span>01 / FOUNDATION</span><h2>Tokens that keep every surface unmistakably Velclaw.</h2></div><div className={styles.foundationGrid}><div className={styles.tokenPanel}><span>COLORS</span><div className={styles.swatches}>{['background','surface','surfaceElevated','border','accent','success','warning','danger'].map(name => <div key={name}><i className={styles[`swatch_${name}` as keyof typeof styles]} /><small>{name}</small></div>)}</div></div><div className={styles.tokenPanel}><span>TYPE</span><div className={styles.typeDemo}><strong>Display / 56</strong><h3>Velclaw</h3><p>Developer infrastructure for agents and software.</p><code>pnpm velclaw deploy</code></div></div><div className={styles.tokenPanel}><span>SPACING</span><div className={styles.spacingDemo}>{[4,8,12,16,24,32,48].map(n => <div key={n}><i style={{width: n * 2}} /><small>{n}px</small></div>)}</div></div></div></section>
    <section className={styles.section}><div className={styles.sectionTitle}><span>02 / COMPONENTS</span><h2>Primitives for build, orchestration and runtime.</h2></div><div className={styles.componentGrid}>{components.map(([name, Icon]) => <div className={styles.componentCard} key={name}><Icon size={18} /><strong>{name}</strong><span>System component</span></div>)}</div><div className={styles.demoGrid}><div className={styles.demoCard}><div className={styles.demoHeader}>STATUS / DEPLOYMENT</div><div className={styles.status}><span className={styles.statusDot} /> Production healthy</div><div className={styles.metric}><b>98.7%</b><span>availability</span></div></div><div className={styles.demoCard}><div className={styles.demoHeader}>CODE / TERMINAL</div><pre><span>$</span> velclaw deploy<br />→ building<br />→ running checks<br /><b>✓ deployment ready</b></pre></div><div className={styles.demoCard}><div className={styles.demoHeader}>ALERT / DIAGNOSTIC</div><div className={styles.alert}><CircleAlert size={16} /><div><b>Build needs attention</b><span>Review the failed workflow step.</span></div></div></div></div></section>
    <section className={styles.section}><div className={styles.sectionTitle}><span>03 / SCREENS</span><h2>One shell, multiple product surfaces.</h2></div><div className={styles.screenList}>{screens.map((screen, i) => <div key={screen}><span>{String(i + 1).padStart(2, '0')}</span><strong>{screen}</strong><small>{i < 9 ? 'Core screen' : 'System screen'}</small><ArrowUpRight size={15} /></div>)}</div></section>
    <section className={styles.section}><div className={styles.sectionTitle}><span>04 / STATES</span><h2>Every operation explains what happened and what to do next.</h2></div><div className={styles.stateGrid}><div className={styles.stateCard}><div className={styles.spinner} /><b>Loading workspace</b><span>Fetching current runtime state…</span></div><div className={styles.stateCard}><div className={styles.emptyIcon}><Terminal size={18} /></div><b>No deployments yet</b><span>Create a release to see deployment activity here.</span><button className={styles.smallButton}>Create deployment</button></div><div className={styles.stateCard}><div className={styles.errorIcon}>!</div><b>Deployment failed</b><span>Open logs to inspect the failed step and retry safely.</span><button className={styles.smallButton}>View logs</button></div></div></section>
    <footer><span className={styles.mark}>V</span><span>VELCLAW DESIGN SYSTEM · BUILD / RUN / UNDERSTAND</span></footer>
  </main>
}
