const DOCS=['getting-started','workspace','agents','build-runtime','github-delivery','security'];
const LABELS={en:{'getting-started':'Getting started',workspace:'Workspace',agents:'Agents & integrations','build-runtime':'Build & runtime','github-delivery':'GitHub delivery',security:'Security'},vi:{'getting-started':'Bắt đầu',workspace:'Workspace',agents:'Agents & tích hợp','build-runtime':'Build & runtime','github-delivery':'GitHub delivery',security:'Bảo mật'}};
const THEME_KEY='velclaw-theme';
function setTheme(theme){document.documentElement.dataset.theme=theme;localStorage.setItem(THEME_KEY,theme)}
function initTheme(){setTheme(localStorage.getItem(THEME_KEY)||'dark')}
function injectFinalStyles(){if(document.querySelector('link[data-velclaw-ui-final]'))return;const link=document.createElement('link');link.rel='stylesheet';link.href='ui-final.css';link.dataset.velclawUiFinal='';document.head.appendChild(link)}
function bindThemeToggle(){const b=document.getElementById('theme-toggle');if(!b)return;const update=()=>{const dark=document.documentElement.dataset.theme!=='light';b.textContent=dark?'☼':'☾';b.setAttribute('aria-label',dark?'Chuyển sang giao diện sáng':'Chuyển sang giao diện tối')};b.onclick=()=>{setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');update()};update()}
function closeMenu(){document.body.classList.remove('menu-open');const b=document.getElementById('menu-toggle');const s=document.querySelector('.sidebar');if(b){b.setAttribute('aria-expanded','false');b.setAttribute('aria-label','Mở menu')}if(s)s.setAttribute('aria-hidden','true')}
function bindMenu(){const b=document.getElementById('menu-toggle'),s=document.querySelector('.sidebar');if(!b)return;if(s)s.setAttribute('aria-hidden','true');b.onclick=e=>{e.stopPropagation();const open=document.body.classList.toggle('menu-open');b.setAttribute('aria-expanded',String(open));b.setAttribute('aria-label',open?'Đóng menu':'Mở menu');if(s)s.setAttribute('aria-hidden',String(!open));if(open)document.getElementById('drawer-close')?.focus()};const close=document.getElementById('drawer-close');if(close)close.onclick=closeMenu;document.addEventListener('click',e=>{if(!document.body.classList.contains('menu-open'))return;if(e.target.closest('.sidebar,.menu-toggle'))return;closeMenu()});document.addEventListener('click',e=>{if(e.target.closest('.sidebar a,.drawer-close'))closeMenu()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()})}
function bindSearch(){const input=document.getElementById('doc-search');if(!input)return;const filter=()=>{const q=input.value.trim().toLowerCase();[...document.querySelectorAll('#sidebar-nav .side-link'),...document.querySelectorAll('#cards .home-card')].forEach(el=>{el.hidden=!!q&&!el.textContent.toLowerCase().includes(q)})};input.addEventListener('input',filter);document.addEventListener('keydown',e=>{if((e.key==='/'||(e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k')&&!/input|textarea|select/i.test(document.activeElement.tagName)){e.preventDefault();input.focus()}})}
function bindToc(){const links=[...document.querySelectorAll('#toc-list a')];const sections=links.map(a=>document.getElementById(a.getAttribute('href').slice(1))).filter(Boolean);if(!links.length||!sections.length)return;const update=()=>{let active=0;const y=window.scrollY+100;sections.forEach((s,i)=>{if(s.offsetTop<=y)active=i});links.forEach((a,i)=>a.classList.toggle('active',i===active));document.querySelectorAll('#mobile-toc-list a').forEach((a,i)=>a.classList.toggle('active',i===active))};window.addEventListener('scroll',update,{passive:true});update()}
initTheme();
document.addEventListener('DOMContentLoaded',()=>{injectFinalStyles();bindThemeToggle();bindMenu();bindSearch()});
window.VELCLAW_DOCS=DOCS;
window.VELCLAW_LABELS=LABELS;