'use client'

import { FormEvent, useEffect, useState } from 'react'

interface Deployment { id:string; projectName:string; repoUrl:string; branch:string; commitSha:string|null; status:string; url:string|null; logs:string[]; error:string|null; createdAt:string }
type DeploymentTarget={projectName:string;repoUrl:string;branch:string;path:string;description:string}
const DEPLOYMENT_TARGETS:DeploymentTarget[]=[{projectName:'velclaw-pages',repoUrl:'https://github.com/Velclaw/deploy-velclaw.git',branch:'main',path:'/',description:'Velclaw public product landing'},{projectName:'velclaw-docs',repoUrl:'https://github.com/Velclaw/velclaw.cfd/docs.git',branch:'main',path:'/docs',description:'Velclaw documentation surface'}]
const DEFAULT_TARGET=DEPLOYMENT_TARGETS[0]
const PIPELINE=['source','ci','build','test','security','approval','deploy','smoke','live'] as const
function stageForStatus(status:string){if(status==='waiting_approval')return 6;if(status==='queued')return 7;if(status==='building')return 7;if(status==='ready')return PIPELINE.length;if(status==='failed')return 5;if(status==='cancelled')return 0;return 1}

export default function VelclawDeployEnginePage(){
 const [deployments,setDeployments]=useState<Deployment[]>([]),[projectName,setProjectName]=useState(DEFAULT_TARGET.projectName),[repoUrl,setRepoUrl]=useState(DEFAULT_TARGET.repoUrl),[branch,setBranch]=useState(DEFAULT_TARGET.branch),[busy,setBusy]=useState(false),[error,setError]=useState(''),[actionId,setActionId]=useState('')
 async function refresh(){const r=await fetch('/api/deployments',{cache:'no-store'});if(!r.ok)return;const d=await r.json();setDeployments(d.deployments||[])}
 useEffect(()=>{void refresh();const t=window.setInterval(()=>void refresh(),5000);return()=>window.clearInterval(t)},[])
 function selectTarget(t:DeploymentTarget){setProjectName(t.projectName);setRepoUrl(t.repoUrl);setBranch(t.branch);setError('')}
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/deployments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectName,repoUrl,branch})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to create release');setDeployments(c=>[d.deployment,...c])}catch(x){setError(x instanceof Error?x.message:'Unable to create release')}finally{setBusy(false)}}
 async function approve(id:string){setActionId(id);setError('');try{const r=await fetch(`/api/deployments/${id}/approve`,{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Approval failed');setDeployments(c=>c.map(x=>x.id===id?d.deployment:x))}catch(x){setError(x instanceof Error?x.message:'Approval failed')}finally{setActionId('')}}
 async function rollback(id:string){setActionId(id);setError('');try{const r=await fetch(`/api/deployments/${id}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'rollback'})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Rollback failed');await refresh()}catch(x){setError(x instanceof Error?x.message:'Rollback failed')}finally{setActionId('')}}
 return <main className="flex-1 overflow-auto p-4 md:p-8"><div className="mx-auto max-w-6xl space-y-6">
  <header><p className="font-mono text-[10px] uppercase tracking-[0.24em] text-violet-300">VELCLAW / DEPLOY CENTER</p><h1 className="mt-2 text-3xl font-semibold">Release Pipeline</h1><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Every production release stops at an explicit approval gate before the deployment worker can claim it.</p></header>
  <section className="grid gap-3 md:grid-cols-2">{DEPLOYMENT_TARGETS.map(t=><article key={t.projectName} className="border border-violet-400/30 bg-violet-500/5 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-mono text-[10px] uppercase tracking-[0.2em] text-violet-300">Deployment target</p><h2 className="mt-1 text-lg font-semibold">{t.projectName}</h2><p className="mt-1 text-xs text-muted-foreground">{t.description} → <span className="font-mono text-violet-300">https://velclaw.cfd{t.path}</span>.</p></div><button type="button" onClick={()=>selectTarget(t)} className="border border-violet-400/60 px-3 py-2 text-xs">Use target</button></div></article>)}</section>
  <form onSubmit={submit} className="grid gap-3 border border-border bg-card p-4 md:grid-cols-4"><label className="space-y-1 text-xs"><span>Project</span><input required className="w-full border border-border bg-background px-3 py-2" value={projectName} onChange={e=>setProjectName(e.target.value)}/></label><label className="space-y-1 text-xs md:col-span-2"><span>GitHub repository</span><input required className="w-full border border-border bg-background px-3 py-2" value={repoUrl} onChange={e=>setRepoUrl(e.target.value)}/></label><label className="space-y-1 text-xs"><span>Branch</span><input required className="w-full border border-border bg-background px-3 py-2" value={branch} onChange={e=>setBranch(e.target.value)}/></label><div className="flex items-center gap-3 md:col-span-4"><button disabled={busy} className="border border-violet-400/60 bg-violet-500/10 px-4 py-2 text-sm disabled:opacity-50">{busy?'Creating…':'Create release'}</button>{error&&<span className="text-xs text-red-300">{error}</span>}</div></form>
  <section className="space-y-3"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Release queue</h2><p className="text-xs text-muted-foreground">Approval is persisted server-side; unapproved releases remain outside the worker queue.</p></div><button type="button" onClick={()=>void refresh()} className="border border-border px-3 py-2 text-xs">Refresh</button></div>
   {deployments.length===0&&<div className="border border-border p-4 text-sm text-muted-foreground">No releases yet.</div>}
   {deployments.map(d=>{const current=stageForStatus(d.status);return <article key={d.id} className="border border-border bg-card p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="font-medium">{d.projectName}</h3><p className="font-mono text-[11px] text-muted-foreground">{d.branch} · {d.id}</p></div><span className="border border-border px-2 py-1 font-mono text-[10px] uppercase">{d.status}</span></div><div className="mt-4 grid gap-1 sm:grid-cols-3 lg:grid-cols-9">{PIPELINE.map((stage,i)=><div key={stage} className={`border p-2 font-mono text-[9px] uppercase ${i+1<=current?'border-violet-400/60 bg-violet-500/10 text-violet-200':'border-border text-muted-foreground'}`}><span className="block">{String(i+1).padStart(2,'0')}</span>{stage}</div>)}</div>{d.status==='waiting_approval'&&<div className="mt-4 flex flex-wrap items-center gap-3 border border-violet-400/40 bg-violet-500/5 p-3"><span className="text-xs">Production deployment is blocked until approved.</span><button type="button" disabled={actionId===d.id} onClick={()=>void approve(d.id)} className="border border-violet-400/70 px-3 py-2 text-xs">{actionId===d.id?'Approving…':'Approve production'}</button></div>}{d.status==='ready'&&<button type="button" disabled={actionId===d.id} onClick={()=>void rollback(d.id)} className="mt-3 border border-red-400/50 px-3 py-2 text-xs text-red-200">{actionId===d.id?'Rolling back…':'Rollback'}</button>}<p className="mt-3 text-xs text-muted-foreground">{d.repoUrl}</p>{d.commitSha&&<p className="mt-1 font-mono text-[10px] text-muted-foreground">commit {d.commitSha}</p>}{d.url&&<a href={d.url} target="_blank" rel="noreferrer" className="mt-2 inline-block text-xs text-violet-300 underline">Open deployment</a>}{d.error&&<p className="mt-2 text-xs text-red-300">{d.error}</p>}<pre className="mt-3 max-h-40 overflow-auto bg-background p-3 text-[11px] leading-5 text-muted-foreground">{(d.logs||[]).join('\n')}</pre></article>})}
  </section></div></main>
}
